language: go
services:
  - mysql
  - postgresql
  - docker
env:
  - AWS_ACCESS_KEY_ID=somekey AWS_SECRET_ACCESS_KEY=somekey PATH=/snap/bin:$PATH CGO_ENABLED=1
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS mouthful_test;'
  - sudo mkdir /mnt/ramdisk
  - sudo mount -t tmpfs -o size=2048m tmpfs /mnt/ramdisk
  - sudo service mysql stop
  - sudo service postgresql stop
  - sudo mv /var/lib/mysql /mnt/ramdisk
  - sudo mv /var/lib/postgresql /mnt/ramdisk
  - sudo ln -s /mnt/ramdisk/mysql /var/lib/mysql
  - sudo ln -s /mnt/ramdisk/postgresql /var/lib/postgresql
  - sudo service mysql start
  - sudo /etc/init.d/postgresql start
  - psql -c 'create database mouthful_test;' -U postgres
  - go get -u github.com/golang/dep/cmd/dep
  - wget http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz -O /tmp/dynamodb_local_latest.tar.gz
  - tar -xzf /tmp/dynamodb_local_latest.tar.gz -C /tmp
  - java -Djava.library.path=/tmp/DynamoDBLocal_lib -jar /tmp/DynamoDBLocal.jar -inMemory &
  - sudo apt-get -y install gcc-multilib
  - sudo apt-get -y install gcc-mingw-w64
install:
  - dep ensure
script: 
  - ./test.sh
  - go build main.go
  - go build cmd/migration/isso/main.go
  - go build cmd/migration/dynamodb/main.go
after_success:
  - bash <(curl -s https://codecov.io/bash)
  # this updates the go report card if we're on master
  - "test $TRAVIS_BRANCH = 'master' && curl -X POST https://goreportcard.com/checks -H 'cache-control: no-cache' -H 'content-type: application/x-www-form-urlencoded' -d 'repo=github.com%2Fvkuznecovas%2Fmouthful'"
notifications:
  email: false
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash -s -- --debug
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
addons:
  hosts:
    - dynamodb-local